// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TT_GeeksForLess_Vladyslav_Slyzkoukhyi;

#nullable disable

namespace TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Migrations
{
    [DbContext(typeof(FolderContext))]
    [Migration("20231106124207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.CreatingDigitalImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvidenceId")
                        .HasColumnType("int");

                    b.Property<int>("GraphicProductId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreatingDigitalImages");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatingDigitalImagesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatingDigitalImagesId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.FinalProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GraphicProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GraphicProductsId");

                    b.ToTable("FinalProducts");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.GraphicProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatingDigitalImagesId")
                        .HasColumnType("int");

                    b.Property<int>("FinalProductId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatingDigitalImagesId");

                    b.ToTable("GraphicProducts");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.PrimarySources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResourcesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourcesId");

                    b.ToTable("PrimarySources");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GraphicProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GraphicProductsId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Resources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatingDigitalImagesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryResourcesId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryResourcesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatingDigitalImagesId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.SecondarySources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResourcesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourcesId");

                    b.ToTable("SecondarySources");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Evidence", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.CreatingDigitalImages", null)
                        .WithMany("Evidence")
                        .HasForeignKey("CreatingDigitalImagesId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.FinalProduct", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.GraphicProducts", null)
                        .WithMany("FinalProduct")
                        .HasForeignKey("GraphicProductsId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.GraphicProducts", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.CreatingDigitalImages", null)
                        .WithMany("GraphicProducts")
                        .HasForeignKey("CreatingDigitalImagesId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.PrimarySources", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Resources", null)
                        .WithMany("PrimaryResources")
                        .HasForeignKey("ResourcesId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Process", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.GraphicProducts", null)
                        .WithMany("Process")
                        .HasForeignKey("GraphicProductsId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Resources", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.CreatingDigitalImages", null)
                        .WithMany("Resources")
                        .HasForeignKey("CreatingDigitalImagesId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.SecondarySources", b =>
                {
                    b.HasOne("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Resources", null)
                        .WithMany("SecondaryResources")
                        .HasForeignKey("ResourcesId");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.CreatingDigitalImages", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("GraphicProducts");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.GraphicProducts", b =>
                {
                    b.Navigation("FinalProduct");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("TT_GeeksForLess_Vladyslav_Slyzkoukhyi.Models.Resources", b =>
                {
                    b.Navigation("PrimaryResources");

                    b.Navigation("SecondaryResources");
                });
#pragma warning restore 612, 618
        }
    }
}
